

import type { Metadata } from "next";
import { VT323 } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import AosProvider from "./components/AosProvider";
import SmoothScroll from "./components/SmoothScroll";
import Footer from "./components/Footer";

const vt323 = VT323({
  variable: "--font-vt323",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Simplicity | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
      <body className={` min-h-full flex flex-col`}>
        <AosProvider />
        <SmoothScroll />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
